#!/usr/bin/env node

var fs = require('fs');
var jsdom = require('jsdom').jsdom;

function evalPasswordComplexity(password, callback) {
  jsdom.env({'html': '<input id="password" value="' + password + '" />',
             'scripts': [__dirname + '/lib/jquery.js',
                         __dirname + '/lib/jquery.complexify.js/jquery.complexify.js'],
             'done': function(errors, window) {
               var $ = window.$;
               var options = {
                 // minimumChars: 8,
                 // strengthScaleFactor: 1,
               };

               $("#password").complexify(options, function(valid, complexity) {
                 callback(null, {"complexity": complexity, "valid": valid});
               });

               $('#password').trigger('keyup');
             }});
}

if (process.argv[2] == undefined) {
  console.error("Evaluate password complexity using jquery.complexify.js.");
  console.error("Exit with an error if complexity is below the threshold.");
  console.error("Usage: " + __filename + " password");
  process.exit(1);
}

evalPasswordComplexity(process.argv[2], function(err, result) {
  console.log(JSON.stringify(result));
  if (!result.valid) {
    process.exit(2);
  }
});
