#!/usr/bin/env node

var complexify = require('./lib/complexify');

if (process.argv[2] == undefined) {
  console.error("Evaluate password complexity using jquery.complexify.js.");
  console.error("Exit with an error if complexity is below the threshold.");
  console.error("Usage: " + __filename + " password");
  process.exit(1);
}

complexify.evalPasswordComplexity(process.argv[2], function(err, result) {
  console.log(JSON.stringify(result));
  if (!result.valid) {
    process.exit(2);
  }
});
